---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  creationTimestamp: null
  labels:
    operators.coreos.com/strimzi-kafka-operator.openshift-operators: ""
  name: strimzi-kafka-operator
  namespace: openshift-operators
spec:
  channel: strimzi-0.19.x
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
