---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    olm.catalogImageTemplate: "icr.io/cpopen/ibm-operator-catalog:v{kube_major_version}.{kube_minor_version}"
  name: ibm-aiops-catalog
  namespace: openshift-marketplace
spec:
  address: ibm-aiops-catalog.openshift-marketplace:50051
  displayName: IBM AIOps Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/aiops-orchestrator-catalog:3.1-latest
  updateStrategy:
    registryPoll:
      interval: 45m
