---
apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  name: ibm-cp-watson-aiops
  namespace: {{.Values.metadata.argocd_app_namespace}}
spec:
{{ if or (not ( eq ( default "" .Values.automation_base_instance_name ) "" )) (not ( eq ( default "" .Values.automation_ui_config_instance_name ) "" )) }}
  automationFoundation:
    {{ if not ( eq ( default "" .Values.automation_base_instance_name ) "" ) }}
    automationBase: {{.Values.automation_base_instance_name}}
    {{ end }}
    {{ if not ( eq ( default "" .Values.automation_ui_config_instance_name ) "" ) }}
    automationUIConfig: {{.Values.automation_ui_config_instance_name}}
    {{ end }}
{{ end }}
  license:
    accept: true
  pakModules:
    - enabled: true
      name: aiManager
      # ROKS override
      # https://www.ibm.com/docs/en/cloud-paks/cp-waiops/3.1.1?topic=troubleshooting-install#custom_overrides
      config:
        - name: aimanager-operator
          spec:
            aimanager:
              minio:
                storage:
                  storageClassName: {{.Values.storageclass.rwx}}
                  storageSize: 100Gi
              postgres:
                storage:
                  enabled: true
                  storageClassName: {{.Values.storageclass.rwx}}
                  storageSize: 20Gi
              storage:
                enabled: true
                storageClassName: {{.Values.storageclass.rwx}}
              elasticsearch:
                storage:
                  enabled: true
                  storageClassName: {{.Values.storageclass.rwx}}
                  storageSize: 100Gi
              flink:
                storage:
                  enabled: true
                  storageClassName: {{.Values.storageclass.rwx}}
                  storageSize: 1Gi
                taskmanager:
                  replicas: 1
                  taskmanagerSlots: 12
              kafka:
                autoTopicCreation: false
                storage:
                  enabled: true
                  storageClassName: {{.Values.storageclass.rwx}}
                  storageSize: 50Gi
              aimanagerValues:
                postgres:
                  livenessProbe:
                    initialDelaySeconds: 300
                    timeoutSeconds: 15
                    failureThreshold: 5
                    periodSeconds: 15
                    successThreshold: 1
                  readinessProbe:
                    initialDelaySeconds: 300
                    timeoutSeconds: 15
                    failureThreshold: 5
                    periodSeconds: 15
                    successThreshold: 1
                  keeper:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                      limits:
                        cpu: 500m
                        memory: 512Mi
                  sentinel:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                      limits:
                        cpu: 500m
                        memory: 512Mi
                  serviceAccount:
                    name: aimanager-operator
                  persistence:
                    enabled: true
                    storageClass: {{.Values.storageclass.rwx}}
                    size: 20Gi
    - enabled: true
      name: aiopsFoundation
    - enabled: true
      name: applicationManager
  size: small
  storageClass: {{.Values.storageclass.rwx}}
  storageClassLargeBlock: {{.Values.storageclass.rwo}}
