---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "110"
  name: >-
    ibm-integration-platform-navigator
  creationTimestamp: null
  namespace: {{.Values.argocd_app_namespace}}
  labels:
    operators.coreos.com/ibm-integration-platform-navigator.ibm-cloudpaks: ''
spec:
  channel: v5.0
  installPlanApproval: Automatic
  name: ibm-integration-platform-navigator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
