---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: gitops-webhook-event-listener-route
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-cicd-event-listener
    weight: 100
  wildcardPolicy: None
