---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  creationTimestamp: null
  name: ibm-cp4ba-anyuid
imagePullSecrets:
  - name: "admin.registrykey"
