---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: ibm-cp-security-operator
  namespace: "{{.Values.metadata.argocd_app_namespace}}"
spec:
  channel: v1.9
  installPlanApproval: Automatic
  name: ibm-cp-security-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
