---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/IBM/cloudpak-gitops.git?ref=main
  creationTimestamp: null
  name: cicd
spec: {}
status: {}
