---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4a-resources
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: {{.Values.metadata.argocd_app_namespace}}
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
        - /spec/source/repoURL
      kind: Application
    - group: icp4a.ibm.com
      jsonPointers:
        - /spec.shared_configuration.sc_deployment_hostname_suffix
      kind: ICP4ACluster
  project: default
  source:
    helm:
      parameters:
        - name: argocd_app_name
          value: ${ARGOCD_APP_NAME}
        - name: argocd_app_namespace
          value: ${ARGOCD_APP_NAMESPACE}
        - name: metadata.argocd_app_namespace
          value: {{.Values.metadata.argocd_app_namespace}}
        - name: storageclass.gold
          value: {{.Values.storageclass.gold}}
        - name: storageclass.silver
          value: {{.Values.storageclass.silver}}
        - name: storageclass.bronze
          value: {{.Values.storageclass.bronze}}
        - name: spec.shared_configuration.sc_deployment_hostname_suffix
          value: {{.Values.spec.shared_configuration.sc_deployment_hostname_suffix}}
        - name: spec.shared_configuration.sc_deployment_platform
          value: {{.Values.spec.shared_configuration.sc_deployment_platform}}
        - name: serviceaccount.argocd_application_controller
          value: {{.Values.serviceaccount.argocd_application_controller}}
    path: config/cloudpaks/cp4a/resources
    repoURL: https://github.com/IBM/cloudpak-gitops.git
  syncPolicy: {}
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
