---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4a-resources
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: {{.Values.metadata.argocd_app_namespace}}
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
    - group: icp4a.ibm.com
      jsonPointers:
        - /spec.shared_configuration.sc_deployment_hostname_suffix
      kind: ICP4ACluster
  project: default
  source:
    helm:
      parameters:
        - name: argocd_app_name
          value: ${ARGOCD_APP_NAME}
        - name: argocd_app_namespace
          value: ${ARGOCD_APP_NAMESPACE}
        - name: metadata.argocd_app_namespace
          value: {{.Values.metadata.argocd_app_namespace}}
        - name: repoURL
          value: ${ARGOCD_APP_SOURCE_REPO_URL}
        - name: serviceaccount.argocd_application_controller
          value: {{.Values.serviceaccount.argocd_application_controller}}
        - name: spec.shared_configuration.sc_deployment_hostname_suffix
          value: {{.Values.spec.shared_configuration.sc_deployment_hostname_suffix}}
        - name: spec.shared_configuration.sc_deployment_platform
          value: {{.Values.spec.shared_configuration.sc_deployment_platform}}
        - name: storageclass.bronze
          value: {{.Values.storageclass.bronze}}
        - name: storageclass.gold
          value: {{.Values.storageclass.gold}}
        - name: storageclass.silver
          value: {{.Values.storageclass.silver}}
        - name: targetRevision
          value: ${ARGOCD_APP_SOURCE_TARGET_REVISION}
    path: config/cloudpaks/cp4a/resources
    repoURL: {{.Values.repoURL}}
    targetRevision: {{.Values.targetRevision}}
  syncPolicy: {}
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
