---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-cloudpaks-cp-shared
  namespace: policy
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
    argocd.argoproj.io/sync-wave: "200"
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-cloudpaks-cp-shared
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: cp-shared-app
                  # Look up used to delay the application of the policy
                  # until this secret is created
                  namespace: '{{ "{{ (lookup \"v1\" \"Secret\" \"openshift-gitops\" \"ibm-entitlement-key\").metadata.namespace }}" }}'
                spec:
                  destination:
                    namespace: "{{.Values.metadata.argocd_app_namespace}}"
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    helm:
                      parameters:
                        - name: argocd_app_name
                          value: ${ARGOCD_APP_NAME}
                        - name: argocd_app_namespace
                          value: ${ARGOCD_APP_NAMESPACE}
                        - name: repoURL
                          value: ${ARGOCD_APP_SOURCE_REPO_URL}
                        - name: serviceaccount.argocd_application_controller
                          value: openshift-gitops-argocd-application-controller
                        - name: targetRevision
                          value: ${ARGOCD_APP_SOURCE_TARGET_REVISION}
                    path: config/argocd-cloudpaks/cp-shared
                    repoURL: {{.Values.repoURL}}
                    targetRevision: '{{ "{{ fromClusterClaim \"gitops-branch\" }}" }}'
                  syncPolicy:
                    automated:
                      selfHeal: true
