---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift
  namespace: policy
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift
  namespace: openshift-config
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift-46
  namespace: policy
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: openshiftVersion
        operator: In
        values:
          - 4.6.30
          - 4.6.31
          - 4.6.32
          - 4.6.33
          - 4.6.34
          - 4.6.35
          - 4.6.36
          - 4.6.37
          - 4.6.38
          - 4.6.39
          - 4.6.40
          - 4.6.41
          - 4.6.42
          - 4.6.43
          - 4.6.44
          - 4.6.45
          - 4.6.46
          - 4.6.47
          - 4.6.48
          - 4.6.49
          - 4.6.50
          - 4.6.51
          - 4.6.52
