name: Merge

on:
  push:
    branches:
      - master
      - main

jobs:
  promote:
    runs-on: ubuntu-latest

    env:
      PIPELINE_DEBUG: 1

    steps:
      - uses: actions/checkout@v3

      - id: setup-action
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - id: release
        name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
